# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 11:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='approvalDate',
            field=models.DateField(default=datetime.datetime(2017, 7, 5, 11, 54, 32, 626697)),
            preserve_default=False,
        ),
    ]
