# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_itemrequest_returndate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='returnDate',
            field=models.DateField(default=b'2017-08-24'),
        ),
    ]
