# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-04 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20170824_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='returnDate',
            field=models.DateField(default=b'2018-02-04'),
        ),
    ]
