# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-13 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20180712_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='returnDate',
            field=models.DateField(default=b'2018-07-13'),
        ),
    ]
