# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-22 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20180722_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='returnDate',
            field=models.DateField(),
        ),
    ]
