# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-04 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20180722_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='approvalDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='returnDate',
            field=models.DateField(null=True),
        ),
    ]
