# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-27 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20180726_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='returnDate',
            field=models.DateField(default=b'2018-07-27'),
        ),
    ]
