# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-02 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20180729_0522'),
        ('inventory', '0010_auto_20180722_0636'),
    ]

    operations = [
    ]
