# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 12:24
from __future__ import unicode_literals

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20170604_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.get_profilepic_path),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=authentication.models.get_resume_path),
        ),
    ]
