# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 17:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_participatedevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='aboutMe',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
