# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-23 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20170803_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
