# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-13 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20180712_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='isemail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='isphone',
            new_name='phone',
        ),
    ]
