# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-26 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20180713_1644'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form',
        ),
    ]
