# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-27 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0004_delete_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
