# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-29 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_form'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form',
        ),
    ]
