# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-29 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
