# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-29 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_auto_20180729_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='year',
            field=models.CharField(max_length=3),
        ),
    ]
