# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-29 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_auto_20180729_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registered',
            name='title',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.DeleteModel(
            name='Registered',
        ),
    ]
