# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-02 19:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0020_auto_20180802_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 8, 2, 19, 23, 1, 154944)),
        ),
    ]
