# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-22 07:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_remove_event_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
                ('isPublished', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventQuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='EventRegisterationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestDate', models.DateField()),
                ('isApproved', models.BooleanField(default=False)),
                ('isParticipated', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='isApprovedUserListPublished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='isEventEnded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='isPublished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='isRegisterationOpen',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='timings',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='organiser',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='eventregisterationrequest',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventRegRequest', to='events.Event'),
        ),
        migrations.AddField(
            model_name='eventregisterationrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventquestionresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionResponse', to='events.Event'),
        ),
        migrations.AddField(
            model_name='eventquestionresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventquestion',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventQuestion', to='events.Event'),
        ),
    ]
