# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-23 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180722_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregisterationrequest',
            name='isApproved',
        ),
    ]
