# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-23 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_eventregisterationrequest_isapproved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregisterationrequest',
            name='isParticipated',
        ),
    ]
