# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-23 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_eventregisterationrequest_isparticipated'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregisterationrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Submitted'), (2, 'Rejected'), (3, 'Approved'), (4, 'Participated')], default=1),
        ),
    ]
