# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-24 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20180723_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregisterationrequest',
            name='requestDate',
            field=models.DateTimeField(),
        ),
    ]
