# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-02 15:23
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20180724_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('phone_no', models.CharField(max_length=100)),
                ('facebook_link', models.CharField(default='#', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='eventName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='enddate',
        ),
        migrations.AddField(
            model_name='event',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.get_banner_path),
        ),
        migrations.AddField(
            model_name='event',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.get_image_path),
        ),
        migrations.AddField(
            model_name='event',
            name='unpaid_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_members',
            field=models.ManyToManyField(blank=True, null=True, to='events.ContactMember'),
        ),
        migrations.AddField(
            model_name='event',
            name='contents',
            field=models.ManyToManyField(blank=True, null=True, related_name='events', to='events.Content'),
        ),
    ]
