# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-02 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20180802_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmember',
            name='facebook_link',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='contact_members',
            field=models.ManyToManyField(blank=True, to='events.ContactMember'),
        ),
        migrations.AlterField(
            model_name='event',
            name='contents',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.Content'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cost',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
