# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-02 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20180802_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
