# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-02 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20180802_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventquestionresponse',
            name='registerationRequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registerationStatus', to='events.EventRegisterationRequest'),
        ),
        migrations.AlterField(
            model_name='contactmember',
            name='facebook_link',
            field=models.CharField(default='#', max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='isRegisterationOpen',
            field=models.BooleanField(default=False),
        ),
    ]
