# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-11 07:01
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20180802_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Submitted'), (2, 'Rejected'), (3, 'Approved'), (4, 'Participated')], default=1)),
                ('message', ckeditor_uploader.fields.RichTextUploadingField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
