# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='branchList',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectDescription',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectName',
            field=models.CharField(max_length=50),
        ),
    ]
