# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170627_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialsUsed', models.TextField(max_length=1000)),
                ('developmentPhases', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=projects.models.get_project_pic_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='projectDescription',
        ),
        migrations.RemoveField(
            model_name='project',
            name='projectImage',
        ),
        migrations.AddField(
            model_name='project',
            name='awards',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='drivingForce',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='endusers',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='impact',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='objective',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='plans',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='teampic',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.get_team_pic_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='shortDesc',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='projectdescription',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
