# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20170702_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdescription',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='desc', to='projects.Project'),
        ),
    ]
