# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkName', models.CharField(max_length=255)),
                ('urlToPage', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='NewsUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=500)),
                ('publishedDate', models.DateField()),
                ('isPublished', models.BooleanField(default=False)),
                ('links', models.ManyToManyField(related_name='news', to='updates.Link')),
            ],
        ),
    ]
