# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 06:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsupdate',
            name='dateAdded',
            field=models.DateField(default=datetime.datetime(2017, 7, 5, 6, 42, 30, 210938)),
            preserve_default=False,
        ),
    ]
