# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_newsupdate_dateadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsupdate',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='news', to='updates.Link'),
        ),
    ]
