# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-08 17:48
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import updates.models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0003_auto_20170705_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to=updates.models.get_picture_path)),
            ],
        ),
    ]
